helloworld/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('website.urls', namespace='website')),
]

website/urls.py
from website.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

app_name = 'website'

urlpatterns = [
    #GET /
    path('', IndexTemplateView.as_view(), name="index"),

    #GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    #GET /funcionario
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    #GET/POST / funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    #GET/POST /funcionario/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

helloworld/models.py
from django.db import models

class Funcionario(models.Model):

    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    sobrenome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    cpf = models.CharField(
        max_length=14,
        null=False,
        blank=False
    )

    tempo_de_servico = models.IntegerField(
        default=0,
        null=False,
        blank=False
    )

    remuneracao = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=False,
        blank=False
    )

    objetos = models.Manager()

website/forms.py
from helloworld.models import Funcionario
from django import forms


class InsereFuncionarioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        model = Funcionario

        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'tempo_de_servico',
            'remuneracao'
        ]

website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from helloworld.models import Funcionario
from website.forms import InsereFuncionarioForm

# PÁGINA PRINCIPAL


class IndexTemplateView(TemplateView):
    template_name = "website/index.html"

# lISTA DE FUNCIONARIOS


class FuncionarioListView(ListView):
    template_name = "website/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"

# CADASTRAMENTO DE FUNCIONÁRIOS


class FuncionarioCreateView(CreateView):
    template_name = "website/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("website:lista_funcionarios")

# ATUALIZAÇÃO DE FUNCIONARIOS


class FuncionarioUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")

# EXCLUSÃO DE FUNCIONÁRIOS


class FuncionarioDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Funcionario
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <title>{% block title %}Sistema de Gerenciamento de Funcionários{% endblock %}</title>

        <link rel="shortcut icon" href="{% static 'website/img/favicon.png' %}" type="img/png">

        <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'website/css/master.css' %}">


        {% block styles %}{% endblock %}
    </head>


        <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'website:index' %}">
                <img src="{% static 'website/img/favicon.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'website:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="{% url 'website:lista_funcionarios' %}">Funcionários</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block conteudo %}{% endblock %}

        <script src="{% static 'website/js/jquery.min.js' %}"></script>
        <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'website/js/scripts.js' %}"></script>
    </body>
</html>

website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Dados do Funcionários{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Atualização de Dados do Funcionário</h5>
                    <form method="post">

                        {% csrf_token %}

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome</span>
                            </div>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Sobrenome</span>
                            </div>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CPF</span>
                            </div>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Tempo de Serviço</span>
                            </div>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Remuneração(p/mês)</span>
                            </div>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>
                        <hr />
                        <div class="text-right">
                            <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-outline-primary">Voltar</a>
                        <button class="btn btn-primary">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Funcionários{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastro de Funcionários</h5>
                    <p class="card-text">
                        Complete o formulário abaixo para cadastrar
                        um novo <code>Funcionário</code>.
                    </p>
                    <form method="post">

                        {% csrf_token %}

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome</span>
                            </div>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Sobrenome</span>
                            </div>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CPF</span>
                            </div>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Tempo de Serviço</span>
                            </div>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Remuneração(p/mês)</span>
                            </div>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>
                        <hr>
                        <div class="text-right">
                            <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-outline-primary">Voltar</a>
                        <button class="btn btn-primary">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/exclui.html
{% extends "website/_layouts/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Exclusão de Funcionário</h5>

            <p class="card-text">
                Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>?
            </p>

            <form method="post">
                {% csrf_token %}

                <hr />
                <div class="text-right">
                    <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-outline-danger">
                        Cancelar
                    </a>
                    <button class="btn btn-danger">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/index.html
{% extends "website/_layouts/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastrar Funcionário</h5>
                    <p class="card-text">
                        Cadastre aqui um novo <code>Funcionário</code>.
                    </p>
                    <a href="{% url 'website:cadastra_funcionario' %}"
                       class="btn btn-primary">
                        Novo Funcionário
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Lista de Funcionários</h5>
                    <p class="card-text">
                        Veja aqui a lista de <code>Funcionários</code> cadastrados.
                    </p>
                    <a href="{% url 'website:lista_funcionarios' %}"
                       class="btn btn-primary">
                        Vá para Lista
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/lista.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Lista de Funcionários</h5>

                    {% if funcionarios|length > 0 %}
                        <p class="card-text">
                            Aqui está a lista de <code>Funcionários</code> cadastrados.
                        </p>

                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Nome</th>
                                <th scope="col">Sobrenome</th>
                                <th scope="col">Tempo de Servico</th>
                                <th scope="col">Remuneração(p/mês)</th>
                                <th scope="col" class="text-center">Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for funcionario in funcionarios %}
                                <tr>
                                    <th scope="row">{{ funcionario.nome|primeira_letra }}</th>
                                    <td>{{ funcionario.nome }}</td>
                                    <td>{{ funcionario.sobrenome }}</td>
                                    <td>{{ funcionario.tempo_de_servico }}</td>
                                    <td>{{ funcionario.remuneracao }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'website:atualiza_funcionario' pk=funcionario.id %}"
                                           class="btn btn-primary">
                                            Atualizar
                                        </a>
                                        <a href="{% url 'website:deleta_funcionario' pk=funcionario.id %}"
                                           class="btn btn-outline-danger">
                                            Excluir
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div class="text-center mt-5 mb-5 jumbotron">
                            <h5>Nenhum <code>Funcionário</code> cadastrado ainda.</h5>
                        </div>
                    {% endif %}
                        <hr />
                        <div class="text-right">
                            <a href="{% url 'website:cadastra_funcionario' %}" class="btn btn-primary">
                                Cadastrar Funcionário
                            </a>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}